name: levit
description: Levit Dart Kit for Dart applications. Includes levit_reactive, levit_scope and levit_dart.
version: 0.0.4
repository: https://github.com/softilab/levit

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  levit_dart: ^0.0.4
  
dev_dependencies:
  test: ^1.24.0
