name: levit_flutter_kit
description: Utility mixins and tools for Levit Flutter applications. Re-exports levit_dart_utility.
version: 0.0.4
repository: https://github.com/softilab/levit

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  levit_dart_kit: ^0.0.4
  levit_flutter: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

