name: levit_stress_tests
description: Pure Dart reactive state management primitives. The engine of the Levit framework.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter 
  levit_reactive:
    path: ../../packages/core/levit_reactive
  levit_scope:
    path: ../../packages/core/levit_scope
  levit_flutter:
    path: ../../packages/kits/levit_flutter_kit
  levit_dart:
    path: ../../packages/core/levit_dart
    
  test: ^1.24.0
  rxdart:
dev_dependencies:
  lints: ^6.0.0

