name: Spelling

on:
  workflow_call:
  workflow_dispatch:

jobs:
  spelling:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run CSpell
        uses: streetsidesoftware/cspell-action@v6
        with:
          config: 'cspell.jsonc'
          # Check the current directory recursively
          files: '.'
          # Fail the build on spelling errors
          strict: true
